### ISSUE TITLE
Fix registrar fetchRetry function.

### ISSUE THREAD

**Issue by vinkabuki** [ZbayApp/waggle#149]
Another registrar issue, never saw it before.

  waggle:io:err Registrar responded with 415 "Unsupported Media Type" (1CEBB86E443A4F34F97082411222EC8E) +46s

**Comment by EmiM** [comment]
I am not sure how you came across the error above. I've been running nectar integration tests many times and only saw this a few times:
```
waggle:io:err Registrar responded with 404 "Not Found (resolve failed)" (88D3F4DE363DF82A7B89AA616476A6E4) +0ms
  nectar:socket Got Error +4s
  nectar:socket {
  nectar:socket   type: 'registrar',
  nectar:socket   message: 'Registering username failed.',
  nectar:socket   communityId: '88D3F4DE363DF82A7B89AA616476A6E4',
  nectar:socket   code: 500
  nectar:socket } +0ms
  nectar:errors received error {
  type: 'registrar',
  message: 'Registering username failed.',
  communityId: '88D3F4DE363DF82A7B89AA616476A6E4',
  code: 500
} +0ms
  nectar:tests User owner starts waiting 120000ms for certificates +0ms
  nectar:tests User owner starts waiting 120000ms for channels +2m
  nectar:tests User owner received 1 channels +7ms
  nectar:tests User userTwo starts waiting 120000ms for channels +0ms
  waggle:io QmdtSNyotYFEuEdSP3eADfLVKsDA1eDQRNBvEqa5MvaahE is subscribing for channel general +4m
  nectar:message sendMessageSaga-1 +0ms
  nectar:message sendMessageSaga-1 +19ms
  nectar:tests User owner starts waiting 120000ms for messages +2m
  waggle:db Writing to public channel db general +6m
  console.error
    TypeError: Cannot read property 'length' of null
        at Object.fromBase64 (/home/rf/dev/zbay/nectar/node_modules/pvutils/src/utils.js:579:18)
        at parseCertificate (/home/rf/dev/zbay/nectar/node_modules/@zbayapp/identity/lib/extractPubKey.js:13:65)
        at runCallEffect (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:528:21)
        at runEffect (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
        at digestEffect (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
        at next (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
        at currCb (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
        at runSelectEffect (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
        at runEffect (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
        at digestEffect (/home/rf/dev/zbay/nectar/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)

      at Object.logError [as onError] (../node_modules/@redux-saga/core/dist/io-1d6eccda.js:115:11)
      at end (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1007:13)
      at abort (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:817:5)
      at Object.task.cont (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:832:9)
      at end (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1016:10)
      at abort (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:817:5)
      at Object.task.cont (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:832:9)
      
console.error
    The above error occurred in task sendMessageSaga
        created by takeEvery(Messages/sendMessage, sendMessageSaga)
        created by messagesMasterSaga
        created by messagesMasterSaga
        created by useIO
        created by useIO
        created by useIO
        created by root
    Tasks cancelled due to error:
    takeEvery(Messages/sendMessage, sendMessageSaga)
    root

      at Object.logError [as onError] (../node_modules/@redux-saga/core/dist/io-1d6eccda.js:116:11)
      at end (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1007:13)
      at abort (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:817:5)
      at Object.task.cont (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:832:9)
      at end (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1016:10)
      at abort (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:817:5)
      at Object.task.cont (../node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:832:9)
```

By the way I think we don't handle errors received from waggle very well (at least in this case): `Cannot read property 'length' of null`

**Comment by vinkabuki** [comment]
The second error occured because of the first one - integration test continues executing even with previous step fails - in this example registration, so it attempted to send a message without being in community. this unsupported media type is very rare, what you got is what we are chasing

**Comment by vinkabuki** [comment]
This is not error received from waggle, but nectar itself
