### ISSUE TITLE
CI - run tests on multiple systems

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/waggle#51]

**Comment by EmiM** [comment]
I managed to run tests on all 3 os. For now it's added to identity repo but it can be easily copied to waggle. 
I used matrix: https://github.com/ZbayApp/identity/pull/1/files#diff-55f05888fd854d9962bdd4d8ccf23a07b610990f58174397b2586b58f8937428
![Screenshot from 2021-06-17 18-31-21](https://user-images.githubusercontent.com/6099829/122439329-d972ec00-cf9b-11eb-9a48-d145c5abc1bb.png)

**Comment by EmiM** [comment]
Running CI on windows takes over 6 minutes because it needs extra dependencies.

**Comment by EmiM** [comment]
https://github.com/ZbayApp/waggle/pull/52 - added in waggle

**Comment by EmiM** [comment]
Thanks to running existing tests on multiple os already I already found (and fixed) some bugs.
I have a problem with one test on windows:
```
Tor manager › should detect and kill old tor process before new tor is spawned

    EBUSY: resource busy or locked, unlink 'C:\Users\RUNNER~1\AppData\Local\Temp\zbayTestTmp_-1040-DbFMtivPrpov\.zbay\TorDataDirectory\lock'

      at rimrafSync (node_modules/tmp/node_modules/rimraf/rimraf.js:303:17)
      at node_modules/tmp/node_modules/rimraf/rimraf.js:336:39
          at Array.forEach (<anonymous>)
      at rmkidsSync (node_modules/tmp/node_modules/rimraf/rimraf.js:336:26)
      at rmdirSync (node_modules/tmp/node_modules/rimraf/rimraf.js:329:7)
      at rimrafSync (node_modules/tmp/node_modules/rimraf/rimraf.js:301:9)
      at node_modules/tmp/node_modules/rimraf/rimraf.js:336:39
          at Array.forEach (<anonymous>)
      at rmkidsSync (node_modules/tmp/node_modules/rimraf/rimraf.js:336:26)
  ```
I am pretty sure that this is just test-config issue or something similar because we don't get this error while running app.
I temporarly removed windows-latest from list of os in ci, windows will be fixed within another task.
