### ISSUE TITLE
Libp2p is connecting only to entry node

### ISSUE THREAD

**Issue by EmiM** [ZbayApp/waggle#77]
We are having a problem with p2p network. It seems like regular nodes are only connecting to entry node and can't connect to other nodes.

**Comment by EmiM** [comment]
```
libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD queue:work +0ms
  libp2p:dht:QmWyprSD findPeerSingle QmceRZyRS3tWYxLvBZV3QfAQ6RPeeAPcSQFBiejKgmiqVg +1ms
  libp2p:dht:net:QmWyprSD sending to: QmceRZyRS3tWYxLvBZV3QfAQ6RPeeAPcSQFBiejKgmiqVg +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD workerQueue:execQuery:  Error: The dial request has no addresses
    at Dialer.connectToPeer (/home/rf/dev/zbay/ZbayLite/node_modules/libp2p/src/dialer/index.js:81:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
    at async Network.sendRequest (/home/rf/dev/zbay/ZbayLite/node_modules/libp2p-kad-dht/src/network.js:129:14) {
  code: 'ERR_NO_VALID_ADDRESSES'
} +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD queue:work:done undefined undefined +1ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD queue:drain +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD worker:stop, 0 workers still running +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD query:done in 1349ms +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD 19 of 20 peers errored (95% fail rate) +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD query:done in 1349ms +0ms
  libp2p:dht:query:QmWppp2zEHrJ2WsGjV2gmGAFZ1RSmFhmdH2uDzcJ3SYQFB:QmWyprSD 19 of 20 peers errored (95% fail rate) +0ms
```
These are the logs from libp2p dht. `workerQueue:execQuery` is a log I added to see what is the error thrown while dialing attempt - "The dial request has no addresses".

**Comment by EmiM** [comment]
https://github.com/ZbayApp/waggle/pull/78

**Comment by EmiM** [comment]
The problem was that we were not calling 'prepareListener' in WebsocketsOverTor. Parent class used 'createListener'. This is weird because we didn't upgrade libp2p-websockets.

**Comment by EmiM** [comment]
Ok, I looked at the git history of the file and found out that the part I fixed yesterday was just removed some time ago.
Commits:
b6c8a384f1545cf723d4375c651afb407bc52f60 <- commented out
77df99ce05ce93763eb3d17d73410dcb716aaae6 <- removed

We all didn't notice that. Proper tests would've caught this.
